name: fwfh_cached_network_image
version: 0.7.0+2
description: WidgetFactory extension to render IMG with cached_network_image plugin.
homepage: https://github.com/daohoangson/flutter_widget_from_html
environment:
  sdk: ">=2.16.0 <3.0.0"
dependencies:
  cached_network_image: ^3.2.2
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.3.0
  flutter_widget_from_html_core:
    git:
      url: https://github.com/vtsindia-dev/flutter_widget_from_html_core.git
dev_dependencies:
  file: any
  flutter_test:
    sdk: flutter
  lint: any
  mocktail: ^0.3.0
